# yamllint disable rule:line-length
# inspired from https://github.com/Poeschl/Hassio-Addons
---
name: Builder

env:
  BUILD_ARGS: ""

on:
  push:
    branches:
      - master
    paths:
      - "**/config.*"

jobs:
  make-executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Make scripts executable
        run: |
          echo "Starting"
          git config core.filemode true
          # shellcheck disable=SC2086,SC2046
          #git update-index --chmod=+x $(find . -type f -iname "*.sh")
          chmod u+x $(find . -type f -iname "*.sh") 
          #git commit -am "fixing the script permissions..."
      - name: Commit if needed
        uses: EndBug/add-and-commit@v9
        with:
          commit: -u
          message: "GitHub bot : scripts executable"
          default_author: github_actions

  check-addon-changes:
    runs-on: ubuntu-latest
    needs: make-executable
    outputs:
      changedAddons: ${{ steps.filter.outputs.changes }}
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v3

      - name: 📂 Detect changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/paths-filter.yml

  lint_config:
    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
    needs: check-addon-changes
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false 
      matrix: 
        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }} 
    steps: 
      - name: ↩️ Checkout 
        uses: actions/checkout@v3
      - name: 🔎 Run Home Assistant Add-on Lint 
        uses: frenck/action-addon-linter@v2 
        with: 
          path: "./${{ matrix.addon }}"

  build:
    if: ${{ needs.check-addon-changes.outputs.changedAddons != '[]' }}
    needs: check-addon-changes
    runs-on: ubuntu-latest
    environment: CR_PAT
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ${{ fromJSON(needs.check-addon-changes.outputs.changedAddons) }}
        arch: ["aarch64", "amd64", "armv7"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Check if add-on should be built
        id: check
        env:
          HEAD: "${{ github.head_ref }}"
        run: |
          # shellcheck disable=SC2157,SC2086 
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
             # shellcheck disable=SC2129
             echo "build_arch=true" >> $GITHUB_OUTPUT;
             # shellcheck disable=SC2129
             echo "image=$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)" >> $GITHUB_OUTPUT;
             if [[ -z "$HEAD" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
                 # shellcheck disable=SC2129
                 echo "BUILD_ARGS=" >> $GITHUB_ENV;
             fi
           else
             echo "${{ matrix.arch }} is not a valid arch for ${{ matrix.addon }}, skipping build";
             # shellcheck disable=SC2129
             echo "build_arch=false" >> $GITHUB_OUTPUT;
          fi
      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS != '--test'
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --image "${{ steps.check.outputs.image }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
